spring.application.name=wallet
server.port=8081
spring.datasource.url=jdbc:mariadb://localhost:3307/mywallet
spring.datasource.username=root
spring.datasource.password=ASSOajmi15#
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
# Set logging level for the entire application
logging.level.root=INFO

# Set logging level for specific packages
logging.level.org.springframework.web=DEBUG
logging.level.com.example=TRACE

# Configure the logging pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n
spring.jpa.database-platform=org.hibernate.dialect.MariaDB103Dialect
# Log file configuration
logging.file.name=app.log
logging.file.path=/var/logs/myapp
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
logging.level.org.hibernate=DEBUG
logging.level.org.springframework.jdbc=DEBUG
spring.security.user.name=yassin
spring.security.user.password=lajmi
spring.devtools.restart.enabled=true
server.error.include-message=always
spring.thymeleaf.cache=false

logging.level.org.thymeleaf=DEBUG